#!/usr/bin/env python3

import json
import sys

# These need to be imported from /opt/python
sys.path.append('/opt/python')
from AwAws.Lambda.extensions import Extension
from AwAws.Utils.env import Env


class SSM_Params_extension(Extension):
    def event_processing(self, event):
        print(f'[MY {self.name}] Received event: {json.dumps(event)}', flush=True)


# Check to see if we want to run this extension
if Env().get_env('AWAWS_SSM_PARAMS') is None:
    print(f'AWAWS_SSM_PARAMS is not set - ssm parameter caching turned off')
else:
    # Run the extension
    ext = SSM_Params_extension()
    ext.register_extension()
    ext.process_events()
